---
- name: Run bootstrap
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    operator_user: dragon
    operator_group: dragon

    cleanup_cloudinit: false
    cleanup_packages_extra:
      - snapd

    required_packages_extra:
      - linux-generic-hwe-22.04
      - python3-netaddr

  roles:
    - osism.commons.operator
    - osism.commons.packages
    - osism.commons.motd
    - osism.services.rng
    - osism.commons.cleanup
    - osism.services.chrony
    - osism.services.lldpd
    - osism.services.journald

- name: Apply role docker
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: true
    docker_configure_storage_driver: true
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_version: "5:24.0.7"
    docker_facts: false

  roles:
    - osism.services.docker

- name: Apply role docker_compose
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  roles:
    - role: osism.commons.docker_compose
