apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://github.com/regiocloud/example-website"
      branch: "main"
      interval: 60
