apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  values:
    ingress:
      enabled: true
      pathType: ImplementationSpecific
      hostname: nginx-flux.<IP>.nip.io
      path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      tls: true
