#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export LANG=en_US.UTF-8
export LANGUAGE=en_US
export LC_ALL=

# install required ansible collections

ansible-galaxy collection install --collections-path /usr/share/ansible/collections ansible.netcommon
ansible-galaxy collection install --collections-path /usr/share/ansible/collections ansible.posix
ansible-galaxy collection install --collections-path /usr/share/ansible/collections community.docker
ansible-galaxy collection install --collections-path /usr/share/ansible/collections community.general

ansible-galaxy collection install --collections-path /usr/share/ansible/collections git+https://github.com/osism/ansible-collection-services
ansible-galaxy collection install --collections-path /usr/share/ansible/collections git+https://github.com/osism/ansible-collection-commons

# run ansible playbook

ansible-playbook -i localhost, /tmp/in_target.d/diskimage.yml

# cleanup

rm -rf /root/.ansible
